server:
  port: 8888

spring:
  cloud:
    config:
      name: config-server
      label: master
      server:
        git:
#          uri: https://@gitlab.com/xxx.git
          uri: https://github.com/gholly/configProperties
          username: yourname
          password: yourpassword
          searchPaths: configPath
    stream:
      kafka:
        binder:
          zk-nodes: localhost:2181
          brokers: localhost:9092
    bus:
      trace:
        enabled: true
      env:
        enabled: true
      refresh:
        enabled: true


endpoints:
  spring:
    cloud:
      bus:
        refresh:
          enabled: true
        env:
        enabled: true
#  rabbitmq:
#    host: localhost
#    port: 5672
#    username: guest
#    password: guest

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8001/eureka/
